backend:
  name: git-gateway
  branch: main
media_folder: "static/img"
public_folder: "/static/img"

collections:
  - name: "post"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
